// src/__tests__/layout.test.tsx
import { render } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import RootLayout from "@/app/layout";
// Hacemos un mock de las fuentes de 'next/font/google'
vi.mock("next/font/google", () => ({
    Poppins: () => ({
        variable: "font-poppins", // Simula la clase de la variable de la fuente
    }),
    Work_Sans: () => ({
        variable: "font-worksans", // Simula la clase de la variable de la fuente
    }),
}));

describe("RootLayout", () => {
    it("should render children correctly", () => {
        const { getByText } = render(
            <RootLayout>
                <div>Test Child</div>
            </RootLayout>
        );

        // Usando el matcher `toBeInTheDocument`
        expect(getByText("Test Child")).toBeInTheDocument();
    });

    it("should apply correct font classes to body", () => {
        const { container } = render(
            <RootLayout>
                <div>Test Child</div>
            </RootLayout>
        );

        const body = container.querySelector("body");
        expect(body).toHaveClass("antialiased");
        expect(body).toHaveClass("font-poppins");
        expect(body).toHaveClass("font-worksans");
    });

    it("should set the correct HTML lang attribute", () => {
        const { container } = render(
            <RootLayout>
                <div>Test Child</div>
            </RootLayout>
        );

        const html = container.querySelector("html");
        expect(html).toHaveAttribute("lang", "en");
    });

    it("should set the correct metadata", () => {
        document.title = "Create Next App";

        const metaDescription = document.createElement("meta");
        metaDescription.setAttribute("name", "description");
        metaDescription.setAttribute("content", "Generated by create next app");
        document.head.appendChild(metaDescription);

        expect(document.title).toBe("Create Next App");

        const meta = document.querySelector("meta[name='description']");
        expect(meta).toHaveAttribute("content", "Generated by create next app");
    });
});
