import type { Metadata } from "next";
import { Poppins, Work_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/navigation/NavBar";
import StackedDivs from "@/app/components/stackedDivsAnimation";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "600", "800"],
    variable: "--font-poppins",
});

const workSans = Work_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "600"],
    style: ["normal", "italic"],
    variable: "--font-worksans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type RootLayoutProps = {
    children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
    return (
        <html lang="es">
        <body className={`${poppins.variable} ${workSans.variable} antialiased`}>
        <StackedDivs/>

        <NavBar/>
        {children}
        </body>
        </html>
    );
}
